### ISSUE TITLE
When recording 

### ISSUE THREAD

**Issue by djr0x** [Giebisch/AutomaticTwitchRecorder#1]
show this error  random and stop  check the streamer and record

ERROR: ffmpeg exited with code -9
Traceback (most recent call last):
  File "/root/master/automatic_twitch_recorder.py", line 74, in <module>
    main(args)
  File "/root/master/automatic_twitch_recorder.py", line 61, in main
    atr.start_loop()
  File "/root/master/automatic_twitch_recorder.py", line 50, in start_loop
    ydl.download([f"http://www.twitch.tv/{self.channel}"])
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffmpeg exited with code -9

please fix 
Thanks

**Comment by Giebisch** [comment]
Can you give a little more insight when this error occured ? At the beginning of the recording, after the stream has finished, ... ?

**Comment by djr0x** [comment]
> Can you give a little more insight when this error occured ? At the beginning of the recording, after the stream has finished, ... ?

hi unfortunately I don't have the complete log, for now it hasn't happened anymore :) thank you very much, from this log you can't understand the problem?

**Comment by djr0x** [comment]
> Can you give a little more insight when this error occured ? At the beginning of the recording, after the stream has finished, ... ?



[twitch:stream] Downloading stream GraphQL
[twitch:stream] Downloading access token JSON
[twitch:stream] 39677168476: Downloading m3u8 information
[twitch:stream] Downloading stream GraphQL
[twitch:stream] Downloading access token JSON
[twitch:stream] 39677168476: Downloading m3u8 information
[download] Destination: None  (live) 2020-10-15 18_08.mp4
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tls @ 0x562a51518e80] Error in the pull function.
https://video-weaver.lhr03.hls.ttvnw.net/v1/playlist/CoEEtEXc45oLXn42RT6iTYQFSw3SdDbhmVvf95UX61r19R0_IWyD9DnmAAqFU-YK2FAMv2OpZx17Iiw3ty0AjmzB2BG8gN04lC5uSk9WACfkRyPoGWacSBl1gWrEvpvifzi-VwINqYw47CQg45zb7cNJbhrXYJrsE1Z3LrD78mmsUXSNC6MKjH3LhzmmO_RLU89MNjTpU57spvKKui0HA5GiHHMLg8JJDRRixiA5aWl3zhOpZ7L3RxOB4JU7Al3mCOKKmSFyCdP-r2hfBL0Hi_zyYtiS9GDTeqza26OoR3G2GuWOjtzMPszDQRm58oLzXM8IPuFJE8SKefSG3fyA4jSbzjrvJlSyfN3NIzzcIPgJlWxTOhLMQ0vTCFrGWo6OoX0-vrKpoHq16InSEYnqztoqTb2mFD9bjqXlvQrB38H5CVHrwxFBSAJC-RFzlkmEVSahdt_MTdr_soRD4nrlvKzr0kzXvSQmJeEsmOD6oUogu7xrhtWxQ9i_6dZGWOIUoTWMfsceHUyIt499cp3QaOHCQH8qvaqA6Up8DaexTWO6xb1mHzvICTC5BBCIDGcGyRy5dQZiekZX5IHnQ_UNYHHykJPoTt20aqDfL6QeRs88KTIyPAHfsdjPmYf7V8jEBFna3ZLZlMseYrhNnYvr_I0onfQhUCxX45zuf76PUkRc8vbxEhB_slsAsUPie6eAkX6_B6xrGgxvvzrzNTdQ5dzLvvY.m3u8: Input/output error


ERROR: ffmpeg exited with code 1
Traceback (most recent call last):
  File "/root/master/automatic_twitch_recorder.py", line 74, in <module>
    main(args)
  File "/root/master/automatic_twitch_recorder.py", line 61, in main
    atr.start_loop()
  File "/root/master/automatic_twitch_recorder.py", line 50, in start_loop
    ydl.download([f"http://www.twitch.tv/{self.channel}"])
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffmpeg exited with code 1



here is the complete log, I just removed the twitch nick, but it does it with other streamers

**Comment by Giebisch** [comment]
I am not able to replicate the error, also I'm not on linux, but it seems to be an input or output error. Try uninstalling youtube-dl and installing it again to get the lastest version and try the new version I just uploaded, hopefully it will work then.

**Comment by djr0x** [comment]
> I am not able to replicate the error, also I'm not on linux, but it seems to be an input or output error. Try uninstalling youtube-dl and installing it again to get the lastest version and try the new version I just uploaded, hopefully it will work then.

Thanks 

    parser.add_argument("--output", type=str, default=os.chdir("/root"), help="Specfiy desired output \

this is correct for folder root? thanks

**Comment by djr0x** [comment]
> I am not able to replicate the error, also I'm not on linux, but it seems to be an input or output error. Try uninstalling youtube-dl and installing it again to get the lastest version and try the new version I just uploaded, hopefully it will work then.

i install without mod file  , and now error istant (it is worse than before :( )



[twitch:stream] matteohs: Downloading stream GraphQL
[twitch:stream] matteohs: Downloading access token JSON
[twitch:stream] 39684361036: Downloading m3u8 information
[twitch:stream] matteohs: Downloading stream GraphQL
[twitch:stream] matteohs: Downloading access token JSON
[twitch:stream] 39684361036: Downloading m3u8 information
[download] Destination: /root/MatteoHS (live) 2020-10-17 03_50.mp4
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tls @ 0x55e38ffbee80] Error in the pull function.
https://video-weaver.lhr03.hls.ttvnw.net/v1/playlist/CoIE4YinaTGxlYBpzFd1Xti7aWtuR2XV3kbo5fT0tRddo1uQrO7nymDxB0DzFUcKngq__o40qXg9DPIbNg1_CoGmtVnXIPngvq9Bzw6E3mCIAsJ5GybqzcUWRWsA0H1oHquEAWZ9svlxRrYUpRYa9_u6_JFDgW1QFRNw6eM7n9VytFCJdoTpb9gXEsbjRAsBd5cT6rvPT3EM9LGn_6pf2BWec1hxwVPAUVZrnKuw1_68yg9Y0wLYbNK2_89YhzpEemQopeF4YyCLCoAjH43pRf178es3rVZefRcwKBIygvNpDzsbFa8g-06P0A6FozbkV_lRn5hDS9hb5d0-LcZC9KoAa97owdtndH-D8cyuA4jxhDMgxAuWoZjzRVaoL88_8miVFskekJhtSwSGnLhDQVd3C4j1yk3epWUl7W7u-3lJHTZas2fKf-H5vWuYwG-rHpm8w8FqJWBu7vWv8RqlFqeHi_v6J7B1qx9ua3BTn6ZiihjjjabM5Os4gRYCBPH4JkJDKjfvRFPk02TGuhKFnN9KEPPPYRCQok3MxdpvmL0I06oOk_Ikk6aBbswvcjUykKrg5-cc65vGOqQhfn3S5u6R0yeSWJcpm2wsB-nzP0Ex5F_M2-CQUnY-piJXIaRbALsYpA1r0UYS5EihvGmD-7s4MnMQMR92yIq56R5un-Bcp3hAahIQKFA2xi3gzuodB_qehP_qqBoMtani1aDkPe0rWdcz.m3u8: Input/output error


ERROR: ffmpeg exited with code 1
Traceback (most recent call last):
  File "/root/master/automatic_twitch_recorder.py", line 74, in <module>
    main(args)
  File "/root/master/automatic_twitch_recorder.py", line 61, in main
    atr.start_loop()
  File "/root/master/automatic_twitch_recorder.py", line 50, in start_loop
    ydl.download([f"http://www.twitch.tv/{self.channel}"])
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffmpeg exited with code 1

**Comment by djr0x** [comment]
> I am not able to replicate the error, also I'm not on linux, but it seems to be an input or output error. Try uninstalling youtube-dl and installing it again to get the lastest version and try the new version I just uploaded, hopefully it will work then.

With this version it gives even more errors, it no longer goes completely:


[twitch:stream] : Downloading stream GraphQL
[twitch:stream] : Downloading access token JSON
[twitch:stream] 39709759356: Downloading m3u8 information
[twitch:stream] : Downloading stream GraphQL
[twitch:stream] : Downloading access token JSON
[twitch:stream] 39709759356: Downloading m3u8 information
[download] Destination: /root/ (live) 2020-10-18 21_09.mp4
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tls @ 0x5640dc08ee80] Error in the pull function.
https://video-weaver.lhr03.hls.ttvnw.net/v1/playlist/CoEEmnLSNOqU8kPodrEUSKhKm-yOVAPkDnG1paDBwUV6xntTVxQBaqfiQjYgTTK6CAUKvNhHbK2gNAtLN0vHHdiKhJ4gyJWmavGqx8G3XTob67xNZ9ftCiVh3nH8eFEt_IXNWaJa4VKk9jtKZmbiGwTxP5mRJC13iY1QMRaTRzLaMZ3dmDn6liNA44rmnwEM0QgIidTtOCL_2UK6UfWLEK1oHHHK-DLmgQ8UVBMYVbJFOAyTPalt5HI-wGWa0L4-KiLww190F7rWvl7EKrC0PoOXYPrirPEHJzyhKuR7OFEVBUx07cc3g7JoWNdU-2ydWxsIyYbnMJzcCHtpXX5Yg6V4yG1ehGxqbaOxlxz8Mrf1hophkIynVy48CzRfNVpMrbJgE-MA0Zv340bYBMTZ9F9eT3IjvPxoLMG3SfHlOTufiXeN3wLYTUBsRXCADKpwAFPom6P4u5AzZzrBS1xiuFvpMGbwRhr2cmEfcPrQlLrau6vso37TW40I5-0MWYRvVcO3i4CIACLdxhFg_yEdd3rRQhFyNk4oA98QFoXUoHcblwv_VfKlV4bW8ITJ0impevSBUcH61TDZ-qKf5cSU9wYn-UAvgP-K9bUgRX9Fp4-qBYnS8rakaunP_pcozt8g84N9iCEeu6EbaDEydDsY62CmCLreYgwOstVsTPn7lbhlUGWqEhCJsH_WbV6FgzN9FPI3ghcyGgwUMOd_yCEoNdNUpxM.m3u8: Input/output error


ERROR: ffmpeg exited with code 1
Traceback (most recent call last):
  File "/root/master/automatic_twitch_recorder.py", line 74, in <module>
    main(args)
  File "/root/master/automatic_twitch_recorder.py", line 61, in main
    atr.start_loop()
  File "/root/master/automatic_twitch_recorder.py", line 50, in start_loop
    ydl.download([f"http://www.twitch.tv/{self.channel}"])
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffmpeg exited with code 1
[root@djandreatest123 ~]# python /root/master/automatic_twitch_recorder.py 
[twitch:stream] : Downloading stream GraphQL
[twitch:stream] : Downloading access token JSON
[twitch:stream] 39709759356: Downloading m3u8 information
[twitch:stream] : Downloading stream GraphQL
[twitch:stream] : Downloading access token JSON
[twitch:stream] 39709759356: Downloading m3u8 information
[download] Destination: /root/ (live) 2020-10-18 21_17.mp4
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tls @ 0x5584feddbe80] Error in the pull function.
https://video-weaver.lhr03.hls.ttvnw.net/v1/playlist/CoEEiqEumXtG1HS7dtX58XIgxuAG51i8gDqnnnZ1CymwCssZmmLhjHbVL2iLX56-HssOm-cDb54BlOKz0rRVditaBxzTxuIjDhi4q_RaS7s90PMe3NnaeA9XaCm_ztNgk-suqzFg2MxY6HWQZeN1yalbTpD5mHMGNspcf43kpmPpbzvsJ0aIth3mkEqcOS0dt_qxfBHIoGfwwumNiXCewV-D0SEtKJlmNUe1GJBY1F0B893A5kvj9pkA-90QwaBAl4vMZqxTXmihfKwH83o1hhZ7N6_dlomosC1I5eXfBfgpwrBLgi5ONnGHHna8wb6GBZe0BzjDyGZVnhml1pHpubg-k7uuQGlUJzd_g_OATzHMYvbi6xNgnhMMGPTz5eRAkQk8GKj_e9QXFEB0m-FMy8KgidymLCmAXUQEn894AjcPh3d5uoIVbvF7EAnubcXTY4I7z319wozbz9_tCys_RUAETnyvrzudGEMyP2U8e7OxjGzdM-KykVBt_k5tbRonKfF6IWVwvQqqPxwkoGLWwLHJXT1WxEkuA8IXPuZjDii0i1vr7lO23FLtyD_XRxzfcRW8HYR0V7OAWHSJs6MQp4M-f6wlAWX7jH5iKNTiF4Z-490Juzr-YCZm7QFY61lnH5EtuNXtJEqiHD1UBXyVSTGEVlfSHY4s3Rh01uvQBKGpoEyhEhBRUpuCP6qg5orsd3ayGnWWGgwpfviG6Iq4IMRAGSI.m3u8: Input/output error


ERROR: ffmpeg exited with code 1
Traceback (most recent call last):
  File "/root/master/automatic_twitch_recorder.py", line 74, in <module>
    main(args)
  File "/root/master/automatic_twitch_recorder.py", line 61, in main
    atr.start_loop()
  File "/root/master/automatic_twitch_recorder.py", line 50, in start_loop
    ydl.download([f"http://www.twitch.tv/{self.channel}"])
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: ffmpeg exited with code 1
